### ISSUE TITLE
Get water tank temperature values as seperate entities

### ISSUE THREAD

**Issue by matthiasfliegner** [cjaliaga/home-assistant-aquarea#113]
Thank you for your great home assistant integration for the Panasonic heat pump!

Currently I only get an "tank" entity consisting of actual and target temperature.

I do need the actual water tank temperature as an individual entity in order to switch on/off an external heater using home assistant.
Would this be possible? 

Thank you for your feedback.

**Comment by DorjeDorf** [comment]
You can do that within HA itself by creating a template sensor. 
It will depend how you have your config files set up and entity naming, but I believe this should be valid for default naming. 

Something like this: 

```
sensor:
  - platform: template
    sensors:
      water_heater_temperature:
        friendly_name: "Water Heater Temperature"
        unit_of_measurement: "°C"  # Use the appropriate unit
        value_template: "{{ state_attr('water_heater.aquarea_tank', 'current_temperature') }}"
```
